interface JPH_ACTION_TYPE {
  JPH_ACTION_REQUEST: string;
  JPH_ACTION_SUCCESS: string;
  JPH_ACTION_FAILURE: string;
}

export const JPH_ACTION: JPH_ACTION_TYPE = {
  JPH_ACTION_REQUEST: "JPH_ACTION_REQUEST",
  JPH_ACTION_SUCCESS: "JPH_ACTION_SUCCESS",
  JPH_ACTION_FAILURE: "JPH_ACTION_FAILURE",
};
